
version: '3.4'
services:
  app:
    container_name: frontend
    image: node:20
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  nginx:
    container_name: front_nginx
    restart: unless-stopped
    image: nginx:latest
    depends_on:
      - app
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Nginx/SSL:/etc/nginx/SSL  # Mount the SSL folder into the container
