services:
  app:
    container_name: frontend
    image: node:20  # Use Node.js 20 from Docker Hub
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: ["npm", "start"]  # Adjust this based on your project setup

  nginx:
    container_name: front_nginx
    restart: unless-stopped
    image: nginx:latest
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
